spring:
  application:
    name: gateway-error
  cloud:
    gateway:
      routes:
        - id: gateway
          uri: https://example.org
          predicates:
            - Host= gateway.lcl
        - id: home
          uri: https://example.org
          predicates:
            - FHost= home.lcl
